baseURL = "/"
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "tobio"
title = "Tobio"
[Languages.en]
contentDir = "content/english"
home = "Home"
languageCode = "pt-pt"
languageName = "Pt"
weight = 1
[Languages.fr]
contentDir = "content/francais"
home = "Accueil"
languageCode = "fr-fr"
languageName = "fr"
weight = 2
[[menu.main]]
name = "WebApp"
url = "http://www.app.tobio.pt"
weight = 1
[[menu.main]]
URL = "#about"
name = "Sobre NÃ³s"
weight = 2
[[menu.main]]
URL = "#blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "#team"
name = "Team"
weight = 4
[[menu.main]]
URL = "#contact"
name = "Contactos"
weight = 5
[params]
author = "toBio"
description = "toBio or not toBio"
google_analitycs_id = ""
logo = "images/tobio.png"
post_share = true
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/687f11ed-1341-4428-a849-fc3829f0a652_200x200 (1).png"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
